# Define a imagem que queremos usar no projeto
FROM node:16.16.0-slim

# Define o diretório que queremos trabalhar dentro do Container
WORKDIR /home/node/app

# Mantem o Container executando indefinidamente
CMD [ "tail", "-f", "/dev/null" ]